# Generated by Django 4.0.4 on 2022-04-16 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='album_name',
        ),
        migrations.RemoveField(
            model_name='show',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='show',
            name='created',
        ),
        migrations.RemoveField(
            model_name='show',
            name='duration',
        ),
        migrations.AddField(
            model_name='show',
            name='image',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='show',
            name='number_of_seasons',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='show',
            name='worth_a_watch',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='title',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='show',
            name='year',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
